export interface Nationality {
  name: string;
  code: string;
}

export const NATIONALITIES: Nationality[] = [
  { name: 'Afghan', code: 'AF' },
  { name: 'Albanian', code: 'AL' },
  { name: 'Algerian', code: 'DZ' },
  { name: 'American', code: 'US' },
  { name: 'Andorran', code: 'AD' },
  { name: 'Angolan', code: 'AO' },
  { name: 'Argentine', code: 'AR' },
  { name: 'Armenian', code: 'AM' },
  { name: 'Australian', code: 'AU' },
  { name: 'Austrian', code: 'AT' },
  { name: 'Azerbaijani', code: 'AZ' },
  { name: 'Bahamian', code: 'BS' },
  { name: 'Bahraini', code: 'BH' },
  { name: 'Bangladeshi', code: 'BD' },
  { name: 'Barbadian', code: 'BB' },
  { name: 'Belarusian', code: 'BY' },
  { name: 'Belgian', code: 'BE' },
  { name: 'Belizean', code: 'BZ' },
  { name: 'Beninese', code: 'BJ' },
  { name: 'Bhutanese', code: 'BT' },
  { name: 'Bolivian', code: 'BO' },
  { name: 'Bosnian', code: 'BA' },
  { name: 'Botswanan', code: 'BW' },
  { name: 'Brazilian', code: 'BR' },
  { name: 'Bruneian', code: 'BN' },
  { name: 'Bulgarian', code: 'BG' },
  { name: 'Burkinabe', code: 'BF' },
  { name: 'Burundian', code: 'BI' },
  { name: 'Cambodian', code: 'KH' },
  { name: 'Cameroonian', code: 'CM' },
  { name: 'Canadian', code: 'CA' },
  { name: 'Cape Verdean', code: 'CV' },
  { name: 'Central African', code: 'CF' },
  { name: 'Chadian', code: 'TD' },
  { name: 'Chilean', code: 'CL' },
  { name: 'Chinese', code: 'CN' },
  { name: 'Colombian', code: 'CO' },
  { name: 'Comoran', code: 'KM' },
  { name: 'Congolese', code: 'CG' },
  { name: 'Costa Rican', code: 'CR' },
  { name: 'Croatian', code: 'HR' },
  { name: 'Cuban', code: 'CU' },
  { name: 'Cypriot', code: 'CY' },
  { name: 'Czech', code: 'CZ' },
  { name: 'Danish', code: 'DK' },
  { name: 'Djiboutian', code: 'DJ' },
  { name: 'Dominican', code: 'DM' },
  { name: 'Dutch', code: 'NL' },
  { name: 'Ecuadorian', code: 'EC' },
  { name: 'Egyptian', code: 'EG' },
  { name: 'Emirati', code: 'AE' },
  { name: 'Equatorial Guinean', code: 'GQ' },
  { name: 'Eritrean', code: 'ER' },
  { name: 'Estonian', code: 'EE' },
  { name: 'Ethiopian', code: 'ET' },
  { name: 'Fijian', code: 'FJ' },
  { name: 'Finnish', code: 'FI' },
  { name: 'French', code: 'FR' },
  { name: 'Gabonese', code: 'GA' },
  { name: 'Gambian', code: 'GM' },
  { name: 'Georgian', code: 'GE' },
  { name: 'German', code: 'DE' },
  { name: 'Ghanaian', code: 'GH' },
  { name: 'Greek', code: 'GR' },
  { name: 'Grenadian', code: 'GD' },
  { name: 'Guatemalan', code: 'GT' },
  { name: 'Guinean', code: 'GN' },
  { name: 'Guyanese', code: 'GY' },
  { name: 'Haitian', code: 'HT' },
  { name: 'Honduran', code: 'HN' },
  { name: 'Hong Konger', code: 'HK' },
  { name: 'Hungarian', code: 'HU' },
  { name: 'Icelandic', code: 'IS' },
  { name: 'Indian', code: 'IN' },
  { name: 'Indonesian', code: 'ID' },
  { name: 'Iranian', code: 'IR' },
  { name: 'Iraqi', code: 'IQ' },
  { name: 'Irish', code: 'IE' },
  { name: 'Israeli', code: 'IL' },
  { name: 'Italian', code: 'IT' },
  { name: 'Ivorian', code: 'CI' },
  { name: 'Jamaican', code: 'JM' },
  { name: 'Japanese', code: 'JP' },
  { name: 'Jordanian', code: 'JO' },
  { name: 'Kazakh', code: 'KZ' },
  { name: 'Kenyan', code: 'KE' },
  { name: 'Kuwaiti', code: 'KW' },
  { name: 'Kyrgyz', code: 'KG' },
  { name: 'Laotian', code: 'LA' },
  { name: 'Latvian', code: 'LV' },
  { name: 'Lebanese', code: 'LB' },
  { name: 'Liberian', code: 'LR' },
  { name: 'Libyan', code: 'LY' },
  { name: 'Liechtensteiner', code: 'LI' },
  { name: 'Lithuanian', code: 'LT' },
  { name: 'Luxembourgish', code: 'LU' },
  { name: 'Macanese', code: 'MO' },
  { name: 'Macedonian', code: 'MK' },
  { name: 'Malagasy', code: 'MG' },
  { name: 'Malawian', code: 'MW' },
  { name: 'Malaysian', code: 'MY' },
  { name: 'Maldivian', code: 'MV' },
  { name: 'Malian', code: 'ML' },
  { name: 'Maltese', code: 'MT' },
  { name: 'Mauritanian', code: 'MR' },
  { name: 'Mauritian', code: 'MU' },
  { name: 'Mexican', code: 'MX' },
  { name: 'Moldovan', code: 'MD' },
  { name: 'Monacan', code: 'MC' },
  { name: 'Mongolian', code: 'MN' },
  { name: 'Moroccan', code: 'MA' },
  { name: 'Mozambican', code: 'MZ' },
  { name: 'Namibian', code: 'NA' },
  { name: 'Nepalese', code: 'NP' },
  { name: 'New Zealander', code: 'NZ' },
  { name: 'Nicaraguan', code: 'NI' },
  { name: 'Nigerian', code: 'NG' },
  { name: 'North Korean', code: 'KP' },
  { name: 'Norwegian', code: 'NO' },
  { name: 'Omani', code: 'OM' },
  { name: 'Pakistani', code: 'PK' },
  { name: 'Palauan', code: 'PW' },
  { name: 'Palestinian', code: 'PS' },
  { name: 'Panamanian', code: 'PA' },
  { name: 'Papua New Guinean', code: 'PG' },
  { name: 'Paraguayan', code: 'PY' },
  { name: 'Peruvian', code: 'PE' },
  { name: 'Filipino', code: 'PH' },
  { name: 'Polish', code: 'PL' },
  { name: 'Portuguese', code: 'PT' },
  { name: 'Qatari', code: 'QA' },
  { name: 'Romanian', code: 'RO' },
  { name: 'Russian', code: 'RU' },
  { name: 'Rwandan', code: 'RW' },
  { name: 'Saint Lucian', code: 'LC' },
  { name: 'Salvadoran', code: 'SV' },
  { name: 'Samoan', code: 'WS' },
  { name: 'Saudi', code: 'SA' },
  { name: 'Senegalese', code: 'SN' },
  { name: 'Serbian', code: 'RS' },
  { name: 'Seychellois', code: 'SC' },
  { name: 'Sierra Leonean', code: 'SL' },
  { name: 'Singaporean', code: 'SG' },
  { name: 'Slovak', code: 'SK' },
  { name: 'Slovenian', code: 'SI' },
  { name: 'Somali', code: 'SO' },
  { name: 'South African', code: 'ZA' },
  { name: 'South Korean', code: 'KR' },
  { name: 'South Sudanese', code: 'SS' },
  { name: 'Spanish', code: 'ES' },
  { name: 'Sri Lankan', code: 'LK' },
  { name: 'Sudanese', code: 'SD' },
  { name: 'Surinamese', code: 'SR' },
  { name: 'Swazi', code: 'SZ' },
  { name: 'Swedish', code: 'SE' },
  { name: 'Swiss', code: 'CH' },
  { name: 'Syrian', code: 'SY' },
  { name: 'Taiwanese', code: 'TW' },
  { name: 'Tajik', code: 'TJ' },
  { name: 'Tanzanian', code: 'TZ' },
  { name: 'Thai', code: 'TH' },
  { name: 'Timorese', code: 'TL' },
  { name: 'Togolese', code: 'TG' },
  { name: 'Tongan', code: 'TO' },
  { name: 'Trinidadian', code: 'TT' },
  { name: 'Tunisian', code: 'TN' },
  { name: 'Turkish', code: 'TR' },
  { name: 'Turkmen', code: 'TM' },
  { name: 'Ugandan', code: 'UG' },
  { name: 'Ukrainian', code: 'UA' },
  { name: 'Uruguayan', code: 'UY' },
  { name: 'Uzbek', code: 'UZ' },
  { name: 'Venezuelan', code: 'VE' },
  { name: 'Vietnamese', code: 'VN' },
  { name: 'Yemeni', code: 'YE' },
  { name: 'Zambian', code: 'ZM' },
  { name: 'Zimbabwean', code: 'ZW' },
];
