<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>LockSoftware</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net20</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="LockSoftware.Reports.bill0.rdlc" />
    <EmbeddedResource Include="LockSoftware.Reports.bill0.rdlc" LogicalName="LockSoftware.Reports.bill0.rdlc" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="ComponentDll">
      <HintPath>..\ZKBiolock\ComponentDll.dll</HintPath>
    </Reference>
    <Reference Include="System.Data" />
    <Reference Include="System.Xml" />
    <Reference Include="Microsoft.ReportViewer.WinForms">
      <HintPath>..\ZKBiolock\Microsoft.ReportViewer.WinForms.dll</HintPath>
    </Reference>
    <Reference Include="DataBase">
      <HintPath>..\ZKBiolock\DataBase.dll</HintPath>
    </Reference>
    <Reference Include="Dev_C_Sharp">
      <HintPath>..\ZKBiolock\Dev_C_Sharp.dll</HintPath>
    </Reference>
    <Reference Include="Interop.Excel">
      <HintPath>..\ZKBiolock\Interop.Excel.dll</HintPath>
    </Reference>
    <Reference Include="Interop.SQLDMO">
      <HintPath>..\ZKBiolock\Interop.SQLDMO.dll</HintPath>
    </Reference>
    <Reference Include="DevExpress.XtraEditors.v10.2" />
  </ItemGroup>
</Project>